'use client'

import { useState } from 'react'
import { useTeamRpc } from '@/lib/use-team-rpc'
import { formatNumber, monthPeriod, validPeriod, type Period, type Statut } from '@/lib/agent-reporting'
import { agencyModel, AGENCY_METRICS, checkAgencyReport, monthlySeries, sixMonths, type AgencyReport } from '@/lib/agency-reporting'
import type { TeamQueue, TeamRanking } from '@/lib/team-reporting'
import { collectionSeries, COMMERCIAL_METRICS, commercialSeries } from '@/lib/network-charts'
import { ChartPanel, CollectionLines, HorizontalBars } from './NetworkCharts'
import { NetworkTable } from './NetworkWorkspace'
import AgentExportButtons from './AgentExportButtons'
import { ReadState, CollectiveGoals, agencyButton as button, agencyInput as input, agencyPanel as panel, type MemberOption, type TeamOption } from './AgencyWorkspace'

export type AgencyAnalysisView = { section: string; group: string; inactive: boolean; tables: Record<string, { page: number; query: string }> }
export const initialAgencyView: AgencyAnalysisView = { section: 'synthese', group: 'collecte', inactive: false, tables: {} }

export default function AgencyAnalytics({ agencyId, onQueue, onTeam, onMember, stats, period, setPeriod, preview, setPreview, view, setView, members, teams }: {
  agencyId: string; onQueue: () => void; onTeam: (id: string) => void; onMember: (id: string) => void;
  stats: boolean; period: Period; setPeriod: (p: Period) => void; preview: boolean; setPreview: (v: boolean) => void;
  view: AgencyAnalysisView; setView: (v: AgencyAnalysisView) => void; members: MemberOption[]; teams: TeamOption[];
}) {
  const [metric, setMetric] = useState('smart'), [business, setBusiness] = useState('reactivations_nb')
  const statuts: Statut[] = preview ? ['en_attente', 'a_corriger', 'validee'] : ['validee']
  const valid = validPeriod(period) && (Date.parse(period.fin) - Date.parse(period.debut)) / 86400000 < 366
  const active = stats ? view.group : view.section
  const report = useTeamRpc<AgencyReport>('rapport_agence', { p_agence_id: agencyId, p_date_debut: period.debut, p_date_fin: period.fin, p_statuts: statuts }, valid)
  const history = useTeamRpc<AgencyReport>('rapport_agence', { p_agence_id: agencyId, p_date_debut: valid ? sixMonths(period.fin)[0].debut : '', p_date_fin: period.fin, p_statuts: statuts }, valid && active === 'evolution')
  const ranking = useTeamRpc<TeamRanking>('classement_agence_membres', { p_agence_id: agencyId, p_date_debut: period.debut, p_date_fin: period.fin, p_inclure_suspendus: view.inactive }, valid && active === 'classement')
  const queue = useTeamRpc<TeamQueue>('agence_file_traitement', { p_agence_id: agencyId, p_taille: 1 }, !stats)
  let data = report.data, consistency = ''
  if (data) { try { checkAgencyReport(data) } catch (e) { consistency = (e as Error).message; data = null } }
  let historic = history.data, historyError = ''
  if (historic) { try { checkAgencyReport(historic) } catch (e) { historyError = (e as Error).message; historic = null } }
  const model = data ? agencyModel(data) : null
  const tabs = stats ? [['collecte', 'Collecte'], ['activite', 'Activité commerciale'], ['ecarts', 'Écarts'], ['evolution', 'Évolution']] : [['synthese', 'Synthèse'], ['equipes', 'Équipes'], ['collaborateurs', 'Collaborateurs'], ['journees', 'Journées'], ['classement', 'Classement']]
  const section = model?.sections.find(s => s.title === ({equipes:'Par équipe', collaborateurs:'Par membre', journees:'Par jour', collecte:'Par jour'} as Record<string,string>)[active])
  const temporal = data ? collectionSeries(data.par_jour, period) : null
  const metrics = AGENCY_METRICS.filter(([key]) => active === 'ecarts' ? /manquant|surplus|regularise|restant/.test(key) : active === 'activite' ? !/smart|caisse|commission|manquant|surplus|regularise|restant|nb_/.test(key) : ['total_smart','total_caisse','total_commission','nb_fiches'].includes(key))
  const chart = (children: React.ReactNode) => <ChartPanel title="Repère visuel de votre agence" preference={'ra-' + active}><p className="mb-4 text-xs text-slate-500">{preview ? 'Prévisualisation · statuts sélectionnés' : 'Officiel · fiches validées'} · {period.debut} → {period.fin} · Recherche du tableau non appliquée</p>{children}</ChartPanel>
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">{stats ? 'Analyse & rapports' : 'Pilotage de l’agence'}</p><h2 className="mt-2 text-3xl font-bold">{stats ? 'Chaque résultat, en détail.' : 'Une vue claire pour décider.'}</h2><p className="mt-2 text-sm text-slate-500">Toute votre agence · Agents et chefs · Contributions des suspendus conservées.</p></div><button className={button} onClick={() => { void report.refresh(); void history.refresh(); void ranking.refresh(); void queue.refresh() }}>Actualiser</button></div>
    {!stats && <><ReadState {...queue} retry={queue.refresh}/>{queue.data && <button onClick={onQueue} className="flex w-full flex-wrap items-center justify-between gap-2 rounded-2xl border border-blue-200 bg-blue-50 p-5 text-left text-blue-950"><strong>{queue.data.compteurs.en_attente} fiche(s) en attente</strong><span className="text-sm">{queue.data.compteurs.a_corriger} à corriger · Toutes dates · Ouvrir la file →</span></button>}</>}
    <section className={panel + ' space-y-4'}><div className="flex flex-wrap items-end gap-3">{(['debut','fin'] as const).map(k => <label key={k} className="text-xs text-slate-500">{k==='debut'?'Du':'Au'}<input type="date" aria-label={k==='debut'?'Début de période':'Fin de période'} className={input+' mt-1'} value={period[k]} onChange={e=>setPeriod({...period,[k]:e.target.value})}/></label>)}<button className={button} onClick={()=>setPeriod(monthPeriod())}>Ce mois</button><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={preview} onChange={e=>setPreview(e.target.checked)}/>Inclure les fiches non validées</label><div className="ml-auto"><AgentExportButtons completeReport disabled={!data || !valid} target={{type:'agence',periode:period,statuts}} scopeSummary={model?.scope}/></div></div>
      <div className="grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2"><label className="text-xs text-slate-500">Consulter une équipe<select aria-label="Consulter une équipe" className={input+' mt-1'} value="" onChange={e=>onTeam(e.target.value)}><option value="">Choisir une équipe…</option>{teams.map(t=><option key={t.id} value={t.id}>{t.nom}</option>)}</select></label><label className="text-xs text-slate-500">Consulter un collaborateur<select aria-label="Consulter un collaborateur" className={input+' mt-1'} value="" onChange={e=>onMember(e.target.value)}><option value="">Choisir un collaborateur…</option>{members.map(m=><option key={m.id} value={m.id}>{m.prenom} {m.nom}</option>)}</select></label></div><p className="text-xs text-slate-500">La consultation détaillée reprend les dates et les statuts sélectionnés. Le rapport d’agence couvre toute l’agence ; la recherche des tableaux ne limite pas l’export.</p>
    </section>
    {!valid && <p role="alert" className="text-red-700">Choisissez une période valide de 366 jours maximum.</p>}<ReadState busy={report.busy} error={report.error || consistency} retry={report.refresh}/>
    {data && <><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[['total_smart','SMART'],['total_caisse','Caisse'],['total_restant','Manquant restant'],['total_surplus_restant','Surplus restant']].map(([key,label])=><article className={panel} key={key}><p className="text-sm text-slate-500">{label}</p><p className="mt-3 break-words text-xl font-bold lg:text-2xl">{formatNumber(Number(data!.synthese[key as keyof typeof data.synthese]))} <span className="text-xs font-normal">FCFA</span></p></article>)}</div><p className="text-xs text-slate-500">{preview?'Prévisualisation':'Officiel · Fiches validées'} · {data.synthese.nb_fiches} fiches · {data.synthese.nb_membres_actifs} membres actifs / {data.synthese.nb_membres} rattachés · {data.synthese.nb_sans_equipe} sans équipe</p>
    <nav aria-label={stats?'Rubriques statistiques agence':'Sections de l’agence'} className="sticky top-20 z-10 flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm">{tabs.map(([key,label])=><button key={key} aria-pressed={active===key} className={'shrink-0 rounded-xl px-4 py-3 text-sm font-semibold '+(active===key?'bg-blue-700 text-white':'text-slate-600 hover:bg-slate-50')} onClick={()=>setView({...view,[stats?'group':'section']:key})}>{label}</button>)}</nav>
    {['synthese','collecte','journees'].includes(active) && chart(temporal && data.synthese.nb_fiches ? <><p className="mb-3 text-xs text-slate-500">Par {temporal.unit} · dates sans collecte à zéro</p><CollectionLines points={temporal.points}/></> : <p className="text-sm text-slate-500">Aucune donnée pour cette sélection.</p>)}
    {['equipes','collaborateurs'].includes(active) && chart(<><label className="mb-4 block text-xs">Indicateur<select aria-label="Indicateur du graphique" className={input+' mt-1 sm:!w-60'} value={metric} onChange={e=>setMetric(e.target.value)}><option value="smart">SMART</option><option value="restant">Manquant restant</option></select></label><HorizontalBars unit="FCFA" points={active==='equipes'?data.par_equipe.map(t=>({label:t.equipe_nom,value:metric==='smart'?t.total_smart:t.total_restant,row:t})):data.par_membre.map(m=>({label:m.prenom+' '+m.nom,value:metric==='smart'?m.total_smart:m.total_manquant_restant,row:m}))} onPoint={p=>{if(active==='equipes'){if(p.row?.equipe_id)onTeam(String(p.row.equipe_id))}else if(p.row?.agent_id)onMember(String(p.row.agent_id))}}/><p className="mt-3 text-xs text-slate-500">Caisse non ventilée à ce niveau dans le rapport actuel. Les sans-équipe sont inclus dans les totaux.</p></>)}
    {active==='activite' && chart(<><select aria-label="Indicateur commercial" className={input+' mb-4 sm:!w-auto'} value={business} onChange={e=>setBusiness(e.target.value)}>{COMMERCIAL_METRICS.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><HorizontalBars unit={COMMERCIAL_METRICS.find(([key])=>key===business)?.[2]?'FCFA':'Nombre'} points={commercialSeries({par_agence:[{agence_id:data.agence.id,agence_nom:data.agence.nom}],par_equipe:data.par_equipe,details_reactivations:data.details_reactivations.map(r=>({...r,agence_id:data.agence.id})),details_augmentations:data.details_augmentations.map(r=>({...r,agence_id:data.agence.id})),details_assurances:data.details_assurances.map(r=>({...r,agence_id:data.agence.id}))},'equipe',business)}/><p className="mt-3 text-xs text-slate-500">Comparaison par équipe · Réactivations effectives uniquement. Les DAT, adhésions et dépôts restent chiffrés ci-dessous.</p></>)}
    {active==='ecarts' && chart(<HorizontalBars unit="FCFA" points={[{label:'Manquant restant',value:data.synthese.total_restant},{label:'Surplus restant',value:data.synthese.total_surplus_restant}]}/>)}
    {stats && active!=='evolution' && <section className={panel}><h3 className="mb-4 font-bold">Indicateurs · {tabs.find(([key])=>key===active)?.[1]}</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([key,label,money])=><div key={key}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold">{formatNumber(data!.synthese[key])}{money?' F':''}</p></div>)}</div>{active==='ecarts'&&<p className="mt-4 text-xs text-slate-500">Restants des fiches de la période. L’onglet Écarts & alertes couvre le suivi de toutes les dates.</p>}</section>}
    {section && <NetworkTable section={section} searchable view={view.tables[active] || {page:1,query:''}} onViewChange={v=>setView({...view,tables:{...view.tables,[active]:v}})} onRow={active==='equipes'?r=>{if(r.equipe_id)onTeam(String(r.equipe_id))}:active==='collaborateurs'?r=>onMember(String(r.agent_id)):undefined}/>}
    {active==='synthese' && <CollectiveGoals type="agence" id={agencyId} date={period.fin}/>}
    {active==='classement' && <section className={panel}><div className="flex flex-wrap justify-between gap-3"><h3 className="font-bold">Classement de l’agence</h3><select aria-label="Périmètre du classement" className={input+' sm:!w-auto'} value={String(view.inactive)} onChange={e=>setView({...view,inactive:e.target.value==='true'})}><option value="false">Membres actifs</option><option value="true">Tous les rattachés</option></select></div><p className="my-3 text-xs text-slate-500">SMART validé · Période sélectionnée · Indépendant de la prévisualisation.</p><ReadState {...ranking} retry={ranking.refresh}/>{ranking.data && <NetworkTable searchable section={{title:'Classement des collaborateurs',columns:[{key:'rang',label:'Rang'},{key:'membre',label:'Collaborateur'},{key:'etat',label:'État'},{key:'total_smart',label:'SMART',money:true}],rows:ranking.data.classement.map(m=>({...m,membre:m.prenom+' '+m.nom,etat:m.actif?'Actif':'Inactif / suspendu'}))}} onRow={r=>onMember(String(r.agent_id))}/>}</section>}
    {active==='evolution' && <><ReadState busy={history.busy} error={history.error || historyError} retry={history.refresh}/>{historic && chart(<><p className="mb-3 text-xs text-slate-500">Six mois se terminant au {period.fin} · Le dernier mois est arrêté à cette date. Le début sélectionné n’est pas utilisé dans cette vue.</p><CollectionLines second={false} points={monthlySeries(historic.par_jour,period.fin).map(m=>({label:m.label,value:m.total}))}/><p className="mt-3 text-xs text-slate-500">L’export principal conserve la période sélectionnée en haut de page.</p></>)}</>}
    </>}
  </div>
}
