'use client'

import { useState } from 'react'
import { ArrowDownRight, ChevronLeft, ChevronRight, FileCheck2, RefreshCw } from 'lucide-react'
import { useTeamRpc } from '@/lib/use-team-rpc'
import { formatDate, formatNumber, todayLome, type Statut } from '@/lib/agent-reporting'
import { type CollectiveObjectives } from '@/lib/agency-reporting'
import type { QueueRow, TeamQueue } from '@/lib/team-reporting'
import ObjectiveProgressCards from './ObjectiveProgressCards'
import { DecisionSheet } from './TeamWorkspace'

export const agencyInput = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100'
export const agencyButton = 'inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 transition hover:border-blue-300 hover:bg-blue-50 focus-visible:outline-2 focus-visible:outline-blue-600 disabled:opacity-40 disabled:cursor-not-allowed'
export const agencyPanel = 'rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm lg:p-6'
export type MemberOption = { id: string; nom: string; prenom: string; equipe_id: string | null }
export type TeamOption = { id: string; nom: string }
export function ReadState({ busy, error, retry }: { busy: boolean; error: string; retry?: () => void }) {
  return <>{busy && <div role="status" className="animate-pulse rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Chargement des données…</div>}{error && <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800">{error}{retry && <button className={agencyButton + ' ml-3'} onClick={retry}>Réessayer</button>}</div>}</>
}
export function CollectiveGoals({ type, id, date = todayLome() }: { type: 'agence' | 'equipe'; id: string; date?: string }) {
  const rpc = useTeamRpc<CollectiveObjectives>('objectifs_collectifs', { p_type_cible: type, p_cible_id: id, p_date: date })
  return <section className={agencyPanel}><h3 className="text-lg font-bold">Objectifs collectifs</h3><p className="mb-5 mt-1 text-sm text-slate-500">Actifs au {formatDate(date)} · Réalisé validé sur la période de chaque objectif.</p><ReadState {...rpc} retry={rpc.refresh}/>{rpc.data && <ObjectiveProgressCards goals={rpc.data.objectifs}/>}</section>
}
export function AgencyQueue({ agencyId, members, teams, onDecision }: { agencyId: string; members: MemberOption[]; teams: TeamOption[]; onDecision: () => void }) {
  const [team, setTeam] = useState(''), [member, setMember] = useState('')
  const [dates, setDates] = useState({ debut: '', fin: '' }), [status, setStatus] = useState<Statut>('en_attente')
  const [page, setPage] = useState(1), [selected, setSelected] = useState<QueueRow | null>(null)
  const valid = !dates.debut || !dates.fin || dates.debut <= dates.fin
  const rpc = useTeamRpc<TeamQueue>('agence_file_traitement', { p_agence_id: agencyId, p_equipe_id: team || null, p_membre_id: member || null, p_date_debut: dates.debut || null, p_date_fin: dates.fin || null, p_statuts: [status], p_page: page, p_taille: 20 }, valid)
  const [focusTarget, setFocusTarget] = useState<HTMLElement | null>(null)
  const selectedIndex = rpc.data?.fiches.findIndex(f=>f.fiche_id===selected?.fiche_id) ?? -1
  const labels = { en_attente: 'En attente', a_corriger: 'À corriger', validee: 'Validées' }
  return <div className="space-y-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Traitement</p><h2 className="mt-2 text-3xl font-bold">Les fiches de votre agence</h2><p className="mt-2 text-sm text-slate-500">Agents et chefs · Plus récentes en premier · Comptes suspendus inclus.</p></div><button className={agencyButton + ' self-start'} onClick={() => void rpc.refresh()} aria-label="Actualiser les fiches"><RefreshCw size={16} /></button></div>
    <div className={agencyPanel + ' grid gap-3 sm:grid-cols-2 xl:grid-cols-4'}><label className="text-xs font-semibold text-slate-500">Équipe<select aria-label="Équipe de la file" className={agencyInput + ' mt-1'} value={team} onChange={e => { setTeam(e.target.value); setMember(''); setPage(1) }}><option value="">Toute l’agence</option>{teams.map(t => <option key={t.id} value={t.id}>{t.nom}</option>)}</select></label><label className="text-xs font-semibold text-slate-500">Collaborateur<select className={agencyInput + ' mt-1'} value={member} onChange={e => { setMember(e.target.value); setPage(1) }}><option value="">Tous les collaborateurs</option>{members.filter(m => !team || m.equipe_id === team).map(m => <option key={m.id} value={m.id}>{m.prenom} {m.nom}</option>)}</select></label>{(['debut','fin'] as const).map(k => <label key={k} className="text-xs font-semibold text-slate-500">{k === 'debut' ? 'Depuis le' : 'Jusqu’au'}<input className={agencyInput + ' mt-1'} type="date" value={dates[k]} onChange={e => { setDates({ ...dates, [k]: e.target.value }); setPage(1) }} /></label>)}</div>
    <div className="flex flex-wrap gap-2">{(['en_attente','a_corriger','validee'] as const).map(s => <button aria-pressed={status === s} key={s} onClick={() => { setStatus(s); setPage(1) }} className={agencyButton + (status === s ? ' !border-blue-700 !bg-blue-700 !text-white' : '')}>{labels[s]} <span className="ml-2 rounded-md bg-black/5 px-2 py-0.5">{rpc.data ? rpc.data.compteurs[s === 'validee' ? 'validees' : s] : '—'}</span></button>)}</div><p className="text-xs text-slate-500">Compteurs pour l’équipe, le collaborateur et les dates sélectionnés, sur toutes les pages.</p>
    {!valid && <p role="alert" className="text-red-700">L’intervalle de dates est invalide.</p>}<ReadState {...rpc} retry={rpc.refresh} />
    {rpc.data && <section className={agencyPanel}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Collaborateur','Journée','Ancienneté','SMART','Caisse',''].map((s,i) => <th key={i} className="whitespace-nowrap px-3 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">{s}</th>)}</tr></thead><tbody>{rpc.data.fiches.map(f => <tr key={f.fiche_id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-3 py-4 font-semibold">{f.prenom} {f.nom}{!f.membre_actif && <span className="block text-xs font-normal text-amber-700">Inactif / suspendu</span>}</td><td className="whitespace-nowrap px-3">{formatDate(f.date)}</td><td className="px-3 text-slate-500">{f.anciennete_jours} j</td><td className="whitespace-nowrap px-3 font-semibold">{formatNumber(f.smart)} F</td><td className="whitespace-nowrap px-3">{formatNumber(f.caisse)} F</td><td className="px-3"><button className={agencyButton} onClick={e => { setFocusTarget(e.currentTarget); setSelected(f) }}>Ouvrir la fiche<ArrowDownRight size={14} /></button></td></tr>)}</tbody></table>{!rpc.data.fiches.length && <div className="py-12 text-center text-slate-500"><FileCheck2 className="mx-auto mb-3" /><p>Aucune fiche pour ces filtres sur cette page.</p></div>}</div><div className="mt-5 flex items-center justify-between gap-3 border-t border-slate-100 pt-4 text-sm"><span>{rpc.data.total_filtre} fiche(s) · Page {page} / {Math.max(1,Math.ceil(rpc.data.total_filtre / 20))}</span><div className="flex gap-2"><button aria-label="Page précédente" className={agencyButton} disabled={page === 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><button aria-label="Page suivante" className={agencyButton} disabled={page * 20 >= rpc.data.total_filtre} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div></div></section>}
    {selected && <DecisionSheet key={selected.fiche_id} drawer restoreFocus={focusTarget} position={`${selectedIndex+1} / ${rpc.data?.fiches.length || 0}`} previous={selectedIndex>0?()=>setSelected(rpc.data!.fiches[selectedIndex-1]):undefined} next={rpc.data && selectedIndex>=0 && selectedIndex<rpc.data.fiches.length-1?()=>setSelected(rpc.data!.fiches[selectedIndex+1]):undefined} row={selected} onClose={() => setSelected(null)} onDone={() => { setSelected(null); void rpc.refresh(); onDecision() }} />}
  </div>
}
