'use client'

import { useState } from 'react'
import { ArrowDownRight, ArrowUpRight, ChevronLeft, ChevronRight, FileCheck2, RefreshCw, TrendingUp } from 'lucide-react'
import { useTeamRpc } from '@/lib/use-team-rpc'
import { formatDate, formatNumber, monthPeriod, todayLome, validPeriod, type Statut, type Period } from '@/lib/agent-reporting'
import { AGENCY_METRICS, checkAgencyReport, monthlySeries, sixMonths, type AgencyReport, type CollectiveObjectives } from '@/lib/agency-reporting'
import type { QueueRow, TeamQueue, TeamRanking } from '@/lib/team-reporting'
import AgentExportButtons from './AgentExportButtons'
import { DecisionSheet } from './TeamWorkspace'

export const agencyInput = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100'
export const agencyButton = 'inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 transition hover:border-blue-300 hover:bg-blue-50 focus-visible:outline-2 focus-visible:outline-blue-600 disabled:opacity-40 disabled:cursor-not-allowed'
export const agencyPanel = 'rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm lg:p-6'
export type MemberOption = { id: string; nom: string; prenom: string; equipe_id: string | null }
export type TeamOption = { id: string; nom: string }
export function ReadState({ busy, error, retry }: { busy: boolean; error: string; retry?: () => void }) {
  return <>{busy && <div role="status" className="animate-pulse rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Chargement des données…</div>}{error && <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800">{error}{retry && <button className={agencyButton + ' ml-3'} onClick={retry}>Réessayer</button>}</div>}</>
}
export function CollectiveGoals({ type, id, date = todayLome() }: { type: 'agence' | 'equipe'; id: string; date?: string }) {
  const rpc = useTeamRpc<CollectiveObjectives>('objectifs_collectifs', { p_type_cible: type, p_cible_id: id, p_date: date })
  return <section className={agencyPanel}><h3 className="text-lg font-bold">Objectifs collectifs</h3><p className="mb-5 mt-1 text-sm text-slate-500">Actifs au {formatDate(date)} · Réalisé validé sur la période de chaque objectif.</p><ReadState {...rpc} retry={rpc.refresh} />{rpc.data?.objectifs.length === 0 && <p className="text-sm text-slate-500">Aucun objectif collectif actif à cette date.</p>}<div className="space-y-6">{rpc.data?.objectifs.map(o => <article key={o.id}><h4 className="font-semibold">{o.titre}</h4><p className="mt-1 text-xs text-slate-500">{formatDate(o.date_debut)} – {formatDate(o.date_fin)}</p>{!o.progressions.length && <p className="mt-2 text-sm text-slate-500">Aucune cible positive renseignée.</p>}<div className="mt-3 grid gap-4 md:grid-cols-2">{o.progressions.map(p => <div key={p.champ} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-3 text-sm"><span>{p.libelle}</span><strong>{p.mesurable && p.pct !== null ? `${formatNumber(p.pct)} %` : 'Non mesuré'}</strong></div><p className="mt-1 text-xs text-slate-500">{p.mesurable && p.realise !== null ? formatNumber(p.realise) : '—'} / {formatNumber(p.cible)}</p>{p.mesurable && p.pct !== null && <div className="mt-2 h-1.5 rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-700" style={{ width: `${Math.min(100, Math.max(0, p.pct))}%` }} /></div>}</div>)}</div></article>)}</div></section>
}
export function AgencyOverview({ agencyId, onQueue, onTeam, onMember, stats = false, period, setPeriod, preview, setPreview }: { agencyId: string; onQueue: () => void; onTeam: (id: string) => void; onMember: (id: string) => void; stats?: boolean; period: Period; setPeriod: (p: Period) => void; preview: boolean; setPreview: (v: boolean) => void }) {
  const [inactive, setInactive] = useState(false)
  const statuts: Statut[] = preview ? ['en_attente','a_corriger','validee'] : ['validee']
  const valid = validPeriod(period) && (Date.parse(period.fin) - Date.parse(period.debut)) / 86400000 < 366
  const report = useTeamRpc<AgencyReport>('rapport_agence', { p_agence_id: agencyId, p_date_debut: period.debut, p_date_fin: period.fin, p_statuts: statuts }, valid)
  const history = useTeamRpc<AgencyReport>('rapport_agence', { p_agence_id: agencyId, p_date_debut: sixMonths(todayLome())[0].debut, p_date_fin: todayLome(), p_statuts: ['validee'] }, !stats)
  const ranking = useTeamRpc<TeamRanking>('classement_agence_membres', { p_agence_id: agencyId, p_date_debut: period.debut, p_date_fin: period.fin, p_inclure_suspendus: inactive }, valid)
  const queue = useTeamRpc<TeamQueue>('agence_file_traitement', { p_agence_id: agencyId, p_taille: 1 }, !stats)
  let data = report.data, consistency = ''
  if (data) { try { checkAgencyReport(data) } catch (e) { consistency = (e as Error).message; data = null } }
  const series = history.data ? monthlySeries(history.data.par_jour, todayLome()) : []
  const max = Math.max(1, ...series.map(s => s.total))
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-700">{stats ? 'Analyse & rapports' : 'Pilotage de l’agence'}</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">{stats ? 'Chaque résultat, en détail.' : 'Une vue claire pour décider.'}</h2><p className="mt-2 text-sm text-slate-500">Agents et chefs rattachés · Contributions des suspendus conservées.</p></div><button className={agencyButton} onClick={() => { void report.refresh(); void history.refresh(); void ranking.refresh(); void queue.refresh() }}><RefreshCw size={16} />Actualiser</button></div>
    {!stats && <><ReadState busy={queue.busy} error={queue.error} retry={queue.refresh} />{queue.data && <button onClick={onQueue} className="flex w-full items-center justify-between gap-4 rounded-2xl border border-blue-200 bg-blue-50 p-5 text-left text-blue-950"><span className="flex items-center gap-3"><FileCheck2 size={24} /><span><strong className="block">{queue.data.compteurs.en_attente} fiche(s) en attente</strong><span className="text-sm text-blue-700">{queue.data.compteurs.a_corriger} à corriger · Toutes dates · Ouvrir la file</span></span></span><ChevronRight size={20} /></button>}</>}
    <div className={agencyPanel + ' flex flex-wrap items-end gap-4'}><label className="text-xs font-semibold text-slate-500">Du<input aria-label="Début de période" type="date" className={agencyInput + ' mt-1'} value={period.debut} onChange={e => setPeriod({ ...period, debut: e.target.value })} /></label><label className="text-xs font-semibold text-slate-500">Au<input aria-label="Fin de période" type="date" className={agencyInput + ' mt-1'} value={period.fin} onChange={e => setPeriod({ ...period, fin: e.target.value })} /></label><button className={agencyButton} onClick={() => setPeriod(monthPeriod())}>Ce mois</button><label className="flex items-center gap-2 py-2 text-sm"><input type="checkbox" checked={preview} onChange={e => setPreview(e.target.checked)} />Inclure les fiches non validées</label><div className="ml-auto"><AgentExportButtons disabled={!data || !!consistency || !valid} target={{ type: 'agence', periode: period, statuts }} /></div></div>
    {!valid && <p role="alert" className="text-sm text-red-700">Choisissez une période valide de 366 jours maximum.</p>}<ReadState busy={report.busy} error={report.error || consistency} retry={report.refresh} />
    {data && <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl bg-gradient-to-br from-blue-950 to-blue-800 p-6 text-white shadow-lg shadow-blue-950/10"><div className="flex justify-between text-blue-200"><span className="text-sm">Collecte SMART</span><TrendingUp size={20} /></div><p className="mt-4 text-3xl font-bold tracking-tight">{formatNumber(data.synthese.total_smart)} <span className="text-sm font-normal">FCFA</span></p><p className="mt-3 text-xs text-blue-200">{preview ? 'Prévisualisation · Tous statuts' : 'Officiel · Fiches validées'}</p></div>{[['total_caisse','Rapporté en caisse'],['total_commission','Commissions'],['total_restant','Manquant restant']].map(([key,label]) => <div key={key} className={agencyPanel}><p className="text-sm text-slate-500">{label}</p><p className="mt-4 text-2xl font-bold tracking-tight">{formatNumber(data.synthese[key as keyof typeof data.synthese])} <span className="text-xs font-normal text-slate-500">FCFA</span></p><p className="mt-3 text-xs text-slate-500">Sur la période sélectionnée</p></div>)}</div><div className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-500"><span><strong className="text-slate-900">{data.synthese.nb_membres_actifs}</strong> membres actifs / {data.synthese.nb_membres} rattachés</span><span>{data.synthese.nb_sans_equipe} sans équipe</span><span>{data.synthese.nb_fiches} fiches retenues</span><span>Surplus restant : <strong className="text-blue-700">{formatNumber(data.synthese.total_surplus_restant)} F</strong></span></div>
    {stats && <section className={agencyPanel}><h3 className="mb-5 text-lg font-bold">Tous les indicateurs</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{AGENCY_METRICS.map(([key,label,money]) => <div key={key} className="border-b border-slate-100 pb-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold tabular-nums">{formatNumber(data!.synthese[key])}{money ? ' F' : ''}</p></div>)}</div></section>}
    <div className="grid gap-6 xl:grid-cols-[1.2fr_1fr]"><section className={agencyPanel}><h3 className="text-lg font-bold">Résultats par équipe</h3><p className="mb-4 mt-1 text-xs text-slate-500">Équipes avec fiches sur la période. L’annuaire contient aussi les équipes sans activité.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="py-3">Équipe</th><th>Fiches</th><th className="text-right">SMART · FCFA</th></tr></thead><tbody>{data.par_equipe.map(t => <tr key={t.equipe_id || 'none'} className="border-t border-slate-100"><td className="py-3">{t.equipe_id ? <button className="font-semibold text-blue-700 hover:underline" onClick={() => onTeam(t.equipe_id!)}>{t.equipe_nom}</button> : 'Sans équipe'}</td><td>{t.nb_fiches}</td><td className="text-right font-semibold tabular-nums">{formatNumber(t.total_smart)}</td></tr>)}</tbody></table>{!data.par_equipe.length && <p className="py-6 text-sm text-slate-500">Aucune fiche sur cette période.</p>}</div></section><section className={agencyPanel}><div className="flex flex-wrap justify-between gap-3"><h3 className="text-lg font-bold">Classement de l’agence</h3><select aria-label="Périmètre du classement" className={agencyInput + ' !w-auto'} value={String(inactive)} onChange={e => setInactive(e.target.value === 'true')}><option value="false">Membres actifs</option><option value="true">Tous les rattachés</option></select></div><p className="my-3 text-xs text-slate-500">SMART validé · Même période · Indépendant de la prévisualisation.</p><ReadState {...ranking} retry={ranking.refresh} /><div className="max-h-80 overflow-y-auto">{ranking.data?.classement.map(m => <button key={m.agent_id} onClick={() => onMember(m.agent_id)} className="flex w-full items-center gap-3 border-b border-slate-100 py-3 text-left text-sm hover:bg-slate-50"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-blue-50 font-bold text-blue-800">{m.rang}</span><span className="flex-1">{m.prenom} {m.nom}{!m.actif && <span className="block text-xs text-amber-700">Inactif / suspendu</span>}</span><strong>{formatNumber(m.total_smart)} F</strong></button>)}{ranking.data?.classement.length === 0 && <p className="py-4 text-sm text-slate-500">Aucun membre dans ce classement.</p>}</div></section></div>
    {stats && <section className={agencyPanel}><h3 className="mb-4 text-lg font-bold">Journal de la période</h3><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Journée','Fiches','SMART','Caisse','Commission'].map(s => <th className="p-3 text-xs text-slate-500" key={s}>{s}</th>)}</tr></thead><tbody>{data.par_jour.map(r => <tr key={String(r.date)} className="border-t border-slate-100"><td className="p-3">{formatDate(String(r.date))}</td>{['nb_fiches','smart','caisse','commission'].map(k => <td className="p-3 tabular-nums" key={k}>{formatNumber(Number(r[k]))}</td>)}</tr>)}</tbody></table>{!data.par_jour.length && <p className="p-3 text-sm text-slate-500">Aucune fiche sur cette période.</p>}</div></section>}</>}
    {!stats && <section className={agencyPanel}><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">Six mois de collecte</h3><p className="mt-1 text-sm text-slate-500">SMART validé · FCFA · Mois courant arrêté à aujourd’hui</p></div><ArrowUpRight className="text-blue-600" /></div><ReadState {...history} retry={history.refresh} /><div className="mt-6 space-y-4">{series.map(m => <div key={m.key} className="grid grid-cols-[5rem_1fr_6rem] items-center gap-3 text-xs"><span className="text-slate-500">{m.label}</span><div className="h-7 rounded-lg bg-slate-100"><div className="h-full rounded-lg bg-blue-700" style={{ width: `${m.total / max * 100}%` }} /></div><strong className="text-right tabular-nums">{formatNumber(m.total)}</strong></div>)}</div></section>}
    <CollectiveGoals type="agence" id={agencyId} date={period.fin || todayLome()} />
  </div>
}

export function AgencyQueue({ agencyId, members, teams, onDecision }: { agencyId: string; members: MemberOption[]; teams: TeamOption[]; onDecision: () => void }) {
  const [team, setTeam] = useState(''), [member, setMember] = useState('')
  const [dates, setDates] = useState({ debut: '', fin: '' }), [status, setStatus] = useState<Statut>('en_attente')
  const [page, setPage] = useState(1), [selected, setSelected] = useState<QueueRow | null>(null)
  const valid = !dates.debut || !dates.fin || dates.debut <= dates.fin
  const rpc = useTeamRpc<TeamQueue>('agence_file_traitement', { p_agence_id: agencyId, p_equipe_id: team || null, p_membre_id: member || null, p_date_debut: dates.debut || null, p_date_fin: dates.fin || null, p_statuts: [status], p_page: page, p_taille: 20 }, valid)
  const labels = { en_attente: 'En attente', a_corriger: 'À corriger', validee: 'Validées' }
  return <div className="space-y-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Traitement</p><h2 className="mt-2 text-3xl font-bold">Les fiches de votre agence</h2><p className="mt-2 text-sm text-slate-500">Agents et chefs · Plus récentes en premier · Comptes suspendus inclus.</p></div><button className={agencyButton + ' self-start'} onClick={() => void rpc.refresh()} aria-label="Actualiser les fiches"><RefreshCw size={16} /></button></div>
    <div className={agencyPanel + ' grid gap-3 sm:grid-cols-2 xl:grid-cols-4'}><label className="text-xs font-semibold text-slate-500">Équipe<select aria-label="Équipe de la file" className={agencyInput + ' mt-1'} value={team} onChange={e => { setTeam(e.target.value); setMember(''); setPage(1) }}><option value="">Toute l’agence</option>{teams.map(t => <option key={t.id} value={t.id}>{t.nom}</option>)}</select></label><label className="text-xs font-semibold text-slate-500">Collaborateur<select className={agencyInput + ' mt-1'} value={member} onChange={e => { setMember(e.target.value); setPage(1) }}><option value="">Tous les collaborateurs</option>{members.filter(m => !team || m.equipe_id === team).map(m => <option key={m.id} value={m.id}>{m.prenom} {m.nom}</option>)}</select></label>{(['debut','fin'] as const).map(k => <label key={k} className="text-xs font-semibold text-slate-500">{k === 'debut' ? 'Depuis le' : 'Jusqu’au'}<input className={agencyInput + ' mt-1'} type="date" value={dates[k]} onChange={e => { setDates({ ...dates, [k]: e.target.value }); setPage(1) }} /></label>)}</div>
    <div className="flex flex-wrap gap-2">{(['en_attente','a_corriger','validee'] as const).map(s => <button aria-pressed={status === s} key={s} onClick={() => { setStatus(s); setPage(1) }} className={agencyButton + (status === s ? ' !border-blue-700 !bg-blue-700 !text-white' : '')}>{labels[s]} <span className="ml-2 rounded-md bg-black/5 px-2 py-0.5">{rpc.data ? rpc.data.compteurs[s === 'validee' ? 'validees' : s] : '—'}</span></button>)}</div><p className="text-xs text-slate-500">Compteurs pour l’équipe, le collaborateur et les dates sélectionnés, sur toutes les pages.</p>
    {!valid && <p role="alert" className="text-red-700">L’intervalle de dates est invalide.</p>}<ReadState {...rpc} retry={rpc.refresh} />
    {rpc.data && <section className={agencyPanel}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Collaborateur','Journée','Ancienneté','SMART','Caisse',''].map((s,i) => <th key={i} className="whitespace-nowrap px-3 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">{s}</th>)}</tr></thead><tbody>{rpc.data.fiches.map(f => <tr key={f.fiche_id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-3 py-4 font-semibold">{f.prenom} {f.nom}{!f.membre_actif && <span className="block text-xs font-normal text-amber-700">Inactif / suspendu</span>}</td><td className="whitespace-nowrap px-3">{formatDate(f.date)}</td><td className="px-3 text-slate-500">{f.anciennete_jours} j</td><td className="whitespace-nowrap px-3 font-semibold">{formatNumber(f.smart)} F</td><td className="whitespace-nowrap px-3">{formatNumber(f.caisse)} F</td><td className="px-3"><button className={agencyButton} onClick={() => setSelected(f)}>Ouvrir la fiche<ArrowDownRight size={14} /></button></td></tr>)}</tbody></table>{!rpc.data.fiches.length && <div className="py-12 text-center text-slate-500"><FileCheck2 className="mx-auto mb-3" /><p>Aucune fiche pour ces filtres sur cette page.</p></div>}</div><div className="mt-5 flex items-center justify-between gap-3 border-t border-slate-100 pt-4 text-sm"><span>{rpc.data.total_filtre} fiche(s) · Page {page} / {Math.max(1,Math.ceil(rpc.data.total_filtre / 20))}</span><div className="flex gap-2"><button aria-label="Page précédente" className={agencyButton} disabled={page === 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><button aria-label="Page suivante" className={agencyButton} disabled={page * 20 >= rpc.data.total_filtre} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div></div></section>}
    {selected && <DecisionSheet key={selected.fiche_id} row={selected} onClose={() => setSelected(null)} onDone={() => { setSelected(null); void rpc.refresh(); onDecision() }} />}
  </div>
}
