 'use client'
import { useEffect, useId, useRef, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { fetchAllRows } from '@/lib/supabase-pagination'
import { useTeamRpc } from '@/lib/use-team-rpc'
import { formatNumber, formatDate, validPeriod, type Period, type ReportRow, type DailyReport } from '@/lib/agent-reporting'
import { networkArgs, networkModel, checkNetworkReport, type NetworkFilters, type NetworkReport } from '@/lib/network-reporting'
import { AGENCY_METRICS, monthlySeries, sixMonths } from '@/lib/agency-reporting'
import { dailyModel, type Section } from '@/lib/agent-export-model'
import { networkPanel as panel, networkInput as input, networkButton as button } from './network-ui'
import AgentExportButtons from './AgentExportButtons'
import NetworkCharts, { ChartPanel } from './NetworkCharts'
export function NetworkState({busy,error,refresh}:{busy:boolean;error:string;refresh:()=>unknown}) { return <>{busy && <p role="status" className="py-6 text-sm text-slate-500">Chargement des données…</p>}{error && <div role="alert" className="my-4 rounded-xl bg-red-50 p-4 text-sm text-red-800"><p>{error}</p><button className={button+' mt-3'} onClick={()=>void refresh()}>Réessayer</button></div>}</> }
type TableView = { page: number; query: string }
export type NetworkOverviewView = { section: string; group: string; tables: Record<string, TableView> }
export const initialOverviewView: NetworkOverviewView = { section: 'agencies', group: 'collecte', tables: {} }
function NetworkTabs({ label, items, value, onChange }: { label: string; items: [string,string][]; value: string; onChange: (v:string)=>void }) {
  return <nav aria-label={label} className="flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm">
    {items.map(([id,title]) => <button key={id} type="button" aria-pressed={value===id} onClick={()=>onChange(id)} className={'shrink-0 rounded-xl px-4 py-3 text-sm font-semibold transition-colors '+(value===id?'bg-blue-700 text-white':'text-slate-600 hover:bg-slate-100')}>{title}</button>)}
  </nav>
}
export function NetworkTable({section,onRow,view,onViewChange,searchable=false}:{section:Section;onRow?:(row:ReportRow)=>void;view?:TableView;onViewChange?:(v:TableView)=>void;searchable?:boolean}) {
  const [local,setLocal]=useState<TableView>({page:1,query:''})
  const state=view || local, update=onViewChange || setLocal
  const rows=section.rows.filter(row=>!searchable || section.columns.some(c=>String(row[c.key] ?? '').toLocaleLowerCase('fr').includes(state.query.toLocaleLowerCase('fr'))))
  const pages=Math.max(1,Math.ceil(rows.length/20)),current=Math.min(state.page,pages)
  return <section className={panel+' min-w-0'}>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">{section.title}</h2>{searchable && <p className="mt-1 text-xs text-slate-500">{rows.length} résultat(s) sur {section.rows.length} · recherche dans ce tableau</p>}</div>{searchable && <input aria-label={'Rechercher dans '+section.title} placeholder="Rechercher…" className={input+' sm:!w-64'} value={state.query} onChange={e=>update({page:1,query:e.target.value})}/>}</div>
    <div className="relative overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{section.columns.map(c=><th key={c.key} className={'whitespace-nowrap border-b px-3 py-3 text-xs font-semibold text-slate-500 '+(c.money?'text-right':'')}>{c.label}</th>)}{onRow && <th className="px-3">Détail</th>}</tr></thead><tbody>{rows.slice((current-1)*20,current*20).map((r,i)=><tr key={i} className="border-b border-slate-100 last:border-0 hover:bg-slate-50">{section.columns.map(c=><td key={c.key} className={'px-3 py-3 '+(c.money?'whitespace-nowrap text-right tabular-nums':'')}>{r[c.key]===null || r[c.key]===undefined?'—':c.money?formatNumber(Number(r[c.key]))+' F':typeof r[c.key]==='boolean'?(r[c.key]?'Oui':'Non'):c.key==='statut'?({validee:'Validée',en_attente:'En attente',a_corriger:'À corriger'}[String(r[c.key])] || String(r[c.key])):String(r[c.key])}</td>)}{onRow && <td className="px-3"><button className="whitespace-nowrap font-semibold text-blue-700" onClick={()=>onRow(r)}>Consulter →</button></td>}</tr>)}</tbody></table></div>
    {pages>1 && <div className="mt-4 flex items-center justify-between gap-3 text-xs"><span>{rows.length} lignes · Page {current}/{pages}</span><div className="flex gap-2"><button className={button} disabled={current===1} onClick={()=>update({...state,page:current-1})}>Précédent</button><button className={button} disabled={current===pages} onClick={()=>update({...state,page:current+1})}>Suivant</button></div></div>}{rows.length===0 && <p className="py-6 text-sm text-slate-500">Aucune donnée pour cette sélection.</p>}
  </section>
}
export function NetworkOverview({filters,period,preview,statistics,onInspect,view,onViewChange}:{filters:NetworkFilters;period:Period;preview:boolean;statistics:boolean;onInspect:(kind:string,id:string|null,agency?:string|null)=>void;view:NetworkOverviewView;onViewChange:(v:NetworkOverviewView)=>void}) {
  const statuts = preview ? ['validee','en_attente','a_corriger'] as const : ['validee'] as const
  const rpc=useTeamRpc<NetworkReport>('rapport_reseau',{...networkArgs(filters),p_date_debut:period.debut,p_date_fin:period.fin,p_statuts:statuts})
  let model:ReturnType<typeof networkModel>|null=null,error=rpc.error
  if(rpc.data)try{model=networkModel(rpc.data)}catch(e){error=(e as Error).message}
  const [level,setLevel]=useState('agence'),[suspended,setSuspended]=useState(false)
  const ranking=useTeamRpc<{ok:true;classement:ReportRow[]}>('classement_reseau',{p_niveau:level,p_date_debut:period.debut,p_date_fin:period.fin,p_inclure_suspendus:suspended,p_agence_id:filters.agenceId,p_equipe_id:level==='agence'?null:filters.equipeId,p_agence_active:filters.agenceActive},!filters.membreId && !statistics && view.section==='ranking')
  const history=useTeamRpc<NetworkReport>('rapport_reseau',{...networkArgs(filters),p_date_debut:sixMonths(period.fin)[0].debut,p_date_fin:period.fin,p_statuts:statuts},statistics && view.group==='evolution')
  let historyError=history.error
  if(history.data)try{checkNetworkReport(history.data)}catch(e){historyError=(e as Error).message}
  const chart=history.data && !historyError ? monthlySeries(history.data.par_jour,period.fin):[],max=Math.max(1,...chart.map(m=>m.total))
  const sectionIndex=['agencies','teams','members','days'].indexOf(view.section)
  const section=model?.sections.find(s=>s.title===['Par agence','Par équipe','Par collaborateur','Par journée'][sectionIndex])
  const tableKey=JSON.stringify({filters,period,preview,section:view.section,level,suspended})
  const tableProps={view:view.tables[tableKey] || {page:1,query:''},onViewChange:(v:TableView)=>onViewChange({...view,tables:{...view.tables,[tableKey]:v}}),searchable:true}
  const core=['total_smart','total_caisse','total_restant','total_surplus_restant']
  const metrics=AGENCY_METRICS.filter(([k])=>view.group==='collecte'?['total_smart','total_caisse','total_commission','nb_fiches','nb_membres','nb_membres_actifs'].includes(k):view.group==='ecarts'?['total_manquant','total_surplus','total_regularise','total_restant','total_surplus_restant'].includes(k):!['nb_fiches','nb_membres','nb_membres_actifs','total_smart','total_caisse','total_commission','total_manquant','total_surplus','total_regularise','total_restant','total_surplus_restant'].includes(k))
  const cards=(items:typeof AGENCY_METRICS[number][])=> <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map(([key,label,money])=><article key={key} className={panel}><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-3 text-2xl font-bold tracking-tight tabular-nums">{formatNumber(rpc.data!.synthese[key])}<span className="ml-1 text-xs font-medium text-slate-400">{money?'FCFA':''}</span></p></article>)}</div>
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><span className={'rounded-full px-3 py-1.5 text-xs font-bold '+(preview?'bg-amber-100 text-amber-900':'bg-emerald-50 text-emerald-800')}>{preview?'PRÉVISUALISATION · tous statuts':'OFFICIEL · fiches validées'}</span><div className="flex flex-wrap items-center gap-3"><button className={button} onClick={()=>{void rpc.refresh();void ranking.refresh();void history.refresh()}}>Actualiser</button><AgentExportButtons completeReport scopeSummary={model?.scope} target={{type:'reseau',filtres:filters,periode:period,statuts:[...statuts]}} disabled={!model || rpc.busy}/></div></div>
    <p className="text-xs text-slate-500">Choisissez un rapport complet ou les sections souhaitées. Les filtres sont toujours inclus ; la recherche du tableau ne limite pas le rapport. Maximum 366 jours.</p>
    <NetworkState {...rpc} error={error}/>
    {model && rpc.data && <>
      {!statistics && cards(AGENCY_METRICS.filter(([k])=>core.includes(k)))}
      <div className="sticky top-2 z-20 bg-slate-50/95 py-2 backdrop-blur"><NetworkTabs label={statistics?'Rubriques statistiques':'Analyses de la vue d’ensemble'} items={statistics?[['collecte','Collecte'],['activite','Activité commerciale'],['ecarts','Écarts'],['evolution','Évolution']]:[['agencies','Agences'],['teams','Équipes'],['members','Collaborateurs'],['days','Journées'],['ranking','Classements']]} value={statistics?view.group:view.section} onChange={value=>onViewChange({...view,...(statistics?{group:value}:{section:value})})}/></div>
      <NetworkCharts report={rpc.data} statistics={statistics} section={view.section} group={view.group} onInspect={onInspect}/>
      {statistics ? view.group==='evolution' ? <ChartPanel preference="stats-evolution" title="Évolution sur six mois"><h2 className="font-bold">SMART · Six mois jusqu’à la date de fin</h2><NetworkState {...history} error={historyError}/><div className="mt-5 space-y-3">{chart.map(m=><div key={m.key} className="grid grid-cols-[5rem_1fr_7rem] items-center gap-3 text-xs"><span>{m.label}</span><div className="h-5 rounded bg-slate-100"><div className="h-5 rounded bg-blue-600" style={{width:`${m.total/max*100}%`}}/></div><strong className="text-right">{formatNumber(m.total)} F</strong></div>)}</div><p className="mt-3 text-xs text-slate-500">Échelle linéaire commune. Le dernier mois s’arrête au {formatDate(period.fin)}.</p></ChartPanel> : cards(metrics) : section && <NetworkTable section={section} {...tableProps} onRow={sectionIndex<3?r=>onInspect(['agencies','teams','members'][sectionIndex],r[['agence_id','equipe_id','agent_id'][sectionIndex]] as string|null,r.agence_id as string|null):undefined}/>}
      {((statistics && view.group==='ecarts') || !statistics) && <p className="text-xs text-slate-500">Les restants concernent les fiches de la période. « Écarts ouverts » présente le stock historique.</p>}
    </>}
    {!statistics && view.section==='ranking' && (filters.membreId?<p className={panel}>Retirez le filtre collaborateur pour comparer les membres du réseau.</p>:<section className={panel}><div className="flex flex-wrap items-center gap-4"><h2 className="mr-auto text-lg font-bold">Classement officiel · SMART validé</h2><select aria-label="Niveau du classement" className={input+' max-w-48'} value={level} onChange={e=>setLevel(e.target.value)}><option value="agence">Agences</option><option value="equipe">Équipes</option><option value="collaborateur">Collaborateurs</option></select><label className="text-xs"><input type="checkbox" checked={suspended} onChange={e=>setSuspended(e.target.checked)}/> Inclure les suspendus</label></div><p className="my-3 text-xs text-slate-500">{level==='agence'?'Le classement des agences est indépendant du filtre équipe.':'Classement du périmètre agence / équipe choisi.'} Les fiches non validées sont toujours exclues.</p><NetworkState {...ranking}/>{ranking.data && <NetworkTable {...tableProps} section={{title:'Résultats',columns:[{key:'rang',label:'Rang'},{key:'label',label:'Cible'},{key:'total_smart',label:'SMART',money:true}],rows:ranking.data.classement.map(r=>({...r,label:r.agence_nom || r.equipe_nom || `${r.prenom || ''} ${r.nom || ''}`}))}}/>}</section>)}
  </div>
}
export function NetworkRecords({filters,period,gaps}:{filters:NetworkFilters;period:Period;gaps:boolean}) {
 const [page,setPage]=useState(1),[status,setStatus]=useState('en_attente'),[type,setType]=useState('tous'),[selected,setSelected]=useState<string|null>(null),[bounded,setBounded]=useState(false),[gapPeriod,setGapPeriod]=useState(period)
 const dates=gaps?(bounded?gapPeriod:null):period
 const args={...networkArgs(filters),p_date_debut:dates?.debut || null,p_date_fin:dates?.fin || null,p_page:page,p_taille:20,...(gaps?{p_type:type}:{p_statuts:status?[status]:['en_attente','a_corriger','validee']})}
 const valid=!dates || validPeriod(dates)
 const rpc=useTeamRpc<{ok:true;total_filtre:number;compteurs:Record<string,number>;fiches?:ReportRow[];ecarts?:ReportRow[]}>(gaps?'ecarts_ouverts':'reseau_file_traitement',args,valid)
 const rows=rpc.data?.[gaps?'ecarts':'fiches'] || []
 const labels:Record<string,string>={en_attente:'En attente',a_corriger:'À corriger',validees:'Validées',nb_manquants_ouverts:'Manquants ouverts',nb_surplus_ouverts:'Surplus ouverts',total_manquant_restant:'Manquant restant · FCFA',total_surplus_restant:'Surplus restant · FCFA'}
 return <div className="space-y-5"><section className={panel}><div className="flex flex-wrap items-center gap-3"><h2 className="mr-auto font-bold">{gaps?'Stock des écarts non soldés':'Suivi des fiches · consultation'}</h2>{gaps?<><select aria-label="Type d’écart" className={input+' max-w-52'} value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="tous">Manquants et surplus</option><option value="manquant">Manquants</option><option value="surplus">Surplus</option></select><label className="text-xs"><input type="checkbox" checked={bounded} onChange={e=>{setBounded(e.target.checked);setPage(1)}}/> Limiter les dates des fiches</label>{bounded && (['debut','fin'] as const).map(k=><input key={k} aria-label={k==='debut'?'Début des écarts':'Fin des écarts'} type="date" className={input+' max-w-44'} value={gapPeriod[k]} onChange={e=>{setGapPeriod({...gapPeriod,[k]:e.target.value});setPage(1)}}/>)}</>:<select aria-label="Statut des fiches" className={input+' max-w-48'} value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="en_attente">En attente</option><option value="a_corriger">À corriger</option><option value="validee">Validées</option><option value="">Tous les statuts</option></select>}</div><p className="mt-3 text-xs text-slate-500">{gaps?'Fiches validées uniquement · Plus gros restants en premier · Les compteurs couvrent les deux types d’écarts.':'Du plus récent au plus ancien · Les compteurs couvrent tous les statuts du périmètre.'}</p></section>{!valid && <p role="alert">Période invalide.</p>}<NetworkState {...rpc}/>{rpc.data && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(rpc.data.compteurs).map(([k,v])=><article className={panel} key={k}><p className="text-xs text-slate-500">{labels[k] || k}</p><p className="mt-2 text-2xl font-bold">{formatNumber(v)}</p></article>)}</div><NetworkTable section={{title:`${rpc.data.total_filtre} fiche(s)`,columns:[{key:'date',label:'Date'},{key:'label',label:'Collaborateur'},{key:'agence_nom',label:'Agence'},{key:'statut',label:'Statut'},{key:'smart',label:'SMART',money:true},{key:gaps?'manquant_restant':'caisse',label:gaps?'Manquant restant':'Caisse',money:true},...(gaps?[{key:'surplus_restant',label:'Surplus restant',money:true}]:[])],rows:rows.map(r=>({...r,label:`${r.prenom} ${r.nom}`}))}} onRow={r=>setSelected(String(r.fiche_id))}/><div className="flex items-center justify-between"><p className="text-xs text-slate-500">Page {page} sur {Math.max(1,Math.ceil(rpc.data.total_filtre/20))}</p><div className="flex gap-2"><button className={button} disabled={page===1} onClick={()=>setPage(page-1)}>Précédent</button><button className={button} disabled={page*20>=rpc.data.total_filtre} onClick={()=>setPage(page+1)}>Suivant</button></div></div></>}{selected && <NetworkFiche id={selected} rows={rows} select={setSelected} close={()=>setSelected(null)}/>}</div>
}
function NetworkFiche({id,rows,select,close}:{id:string;rows:ReportRow[];select:(id:string)=>void;close:()=>void}) {
  const rpc=useTeamRpc<DailyReport>('rapport_fiche_journaliere',{p_fiche_id:id})
  const dialog=useRef<HTMLDialogElement>(null),body=useRef<HTMLDivElement>(null),titleId=useId()
  const [section,setSection]=useState('summary')
  useEffect(()=>{
    const trigger=document.activeElement as HTMLElement|null,oldOverflow=document.body.style.overflow
    const element=dialog.current
    element?.showModal(); document.body.style.overflow='hidden'
    return ()=>{element?.close();document.body.style.overflow=oldOverflow;trigger?.focus({preventScroll:true})}
  },[])
  useEffect(()=>{if(body.current)body.current.scrollTop=0},[id,section])
  let model:ReturnType<typeof dailyModel>|null=null,error=rpc.error
  if(rpc.data)try{model=dailyModel(rpc.data)}catch{error='Rapport incomplet. Actualisez.'}
  const index=rows.findIndex(r=>r.fiche_id===id),row=rows[index]
  const move=(delta:number)=>{const next=rows[index+delta];if(next)select(String(next.fiche_id))}
  const sections=model?.sections.filter(s=>section==='summary'?['Synthèse','Informations'].includes(s.title):!['Synthèse','Informations'].includes(s.title)) || []
  return <dialog ref={dialog} aria-labelledby={titleId} onCancel={e=>{e.preventDefault();close()}} className="fixed inset-y-0 right-0 left-auto m-0 h-dvh max-h-none w-full max-w-none border-0 bg-slate-50 p-0 text-slate-900 shadow-2xl backdrop:bg-slate-950/50 sm:w-[min(900px,85vw)]" style={{fontFamily:'var(--font-dm-sans), sans-serif'}}>
    <div className="flex h-full flex-col"><header className="shrink-0 border-b border-slate-200 bg-white p-4 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Fiche journalière · Lecture seule</p><h2 id={titleId} className="mt-2 text-xl font-bold">{row?`${row.prenom} ${row.nom}`:'Détail de la fiche'}</h2><p className="mt-1 text-sm text-slate-500">{row?.date?formatDate(String(row.date)):model?.period} · {model?.status || 'Chargement…'}</p></div><button autoFocus className={button} onClick={close}>Fermer le détail</button></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><button className={button} disabled={index<=0} onClick={()=>move(-1)}>Fiche précédente</button><button className={button} disabled={index<0 || index>=rows.length-1} onClick={()=>move(1)}>Fiche suivante</button></div><AgentExportButtons target={{type:'fiche',ficheId:id}} disabled={!model}/></div><p className="mt-2 text-xs text-slate-400">{index>=0?`Fiche ${index+1} sur ${rows.length} dans cette page`:'La fiche n’est plus dans la sélection actuelle.'}</p></header>
    <div className="shrink-0 px-4 pt-4 sm:px-6"><NetworkTabs label="Rubriques de la fiche" items={[["summary","Synthèse"],["activity","Activités"],["history","Régularisations"]]} value={section} onChange={setSection}/></div>
    <div ref={body} className="min-h-0 flex-1 space-y-4 overflow-y-auto p-4 sm:p-6"><NetworkState {...rpc} error={error}/>{model && (section==='history'?<NetworkHistory key={id} id={id}/>:sections.map(s=><NetworkTable key={id+s.title} section={s}/>))}</div></div>
  </dialog>
}

function NetworkHistory({id}:{id:string}) {
 const [rows,setRows]=useState<ReportRow[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(true),[version,setVersion]=useState(0)
 useEffect(()=>{let live=true;async function load(){try{const r=await fetchAllRows<ReportRow>((from,to)=>supabase.from('regularisations').select('id,created_at,montant,type_ecart,numero_compte,nom_client,commentaire,piece_jointe_url,piece_jointe_nom').eq('fiche_id',id).order('created_at',{ascending:false}).order('id').range(from,to));if(r.error)throw new Error('Historique indisponible ou accès refusé.');if(live){setRows(r.data || []);setError('')}}catch(e){if(live)setError((e as Error).message)}finally{if(live)setBusy(false)}}void load();return()=>{live=false}},[id,version])
 return <section className={panel}><h3 className="font-bold">Historique des régularisations</h3><NetworkState busy={busy} error={error} refresh={()=>{setBusy(true);setVersion(v=>v+1)}}/>{!busy && !error && (rows.length?rows.map(r=><article key={String(r.id)} className="mt-3 rounded-xl bg-slate-50 p-4"><p className="text-sm font-bold">{formatNumber(Number(r.montant))} FCFA · {r.type_ecart}</p><p className="mt-1 text-xs text-slate-500">{String(r.created_at)} · {r.commentaire || 'Sans commentaire'}</p>{r.numero_compte && <p className="text-xs">Compte {r.numero_compte} · {r.nom_client}</p>}{typeof r.piece_jointe_url==='string' && /^https:\/\//i.test(r.piece_jointe_url) && <a className="mt-2 inline-block text-sm text-blue-700 underline" href={r.piece_jointe_url} target="_blank" rel="noopener noreferrer">{r.piece_jointe_nom || 'Consulter le justificatif'}</a>}</article>):<p className="mt-3 text-sm text-slate-500">Aucune régularisation enregistrée.</p>)}</section>
}
