// Synthetic browser recipe. Every Supabase request is intercepted; no production data.
const fs=require('node:fs'),assert=require('node:assert/strict')
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright')
async function main(){
 const report=JSON.parse(fs.readFileSync('.next/lot7-validation/fixture.json','utf8')),network=JSON.parse(fs.readFileSync('.next/lot9-validation/fixture.json','utf8'))
  network.par_agence.push(...Array.from({length:25},(_,i)=>({agence_id:`90000000-0000-4000-8000-${String(i).padStart(12,'0')}`,agence_nom:`Agence supplémentaire ${i}`,nb_fiches:0,total_smart:0,total_caisse:0,total_restant:0,total_surplus_restant:0})))
  const config=fs.readFileSync('.env.local','utf8'),url=config.match(/NEXT_PUBLIC_SUPABASE_URL\s*=\s*["']?(https:\/\/[^\s"']+)/)?.[1];assert.ok(url)
  const ref=new URL(url).hostname.split('.')[0],id=report.agence.id,member=report.par_membre[1].agent_id
  const user={id,aud:'authenticated',role:'authenticated',email:'fixture@example.invalid',app_metadata:{provider:'email',providers:['email']},user_metadata:{},created_at:'2026-01-01T00:00:00Z'}
  const jwt=[Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),Buffer.from(JSON.stringify({sub:id,role:'authenticated',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'synthetic-signature'].join('.')
  const session={access_token:jwt,refresh_token:'synthetic-refresh',token_type:'bearer',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,user}
  const browser=await chromium.launch({channel:'chrome',headless:true})
  try{
    const context=await browser.newContext({viewport:{width:1440,height:1000}})
    await context.addCookies([{name:`sb-${ref}-auth-token`,value:'base64-'+Buffer.from(JSON.stringify(session)).toString('base64url'),domain:'localhost',path:'/'}])
    await context.routeWebSocket('**/realtime/**',ws=>ws.onMessage(()=>{}))

    const calls=[],writes=[],errors=[],consoleErrors=[],exports=[];let writeFail=true
    const goal={id:'77777777-7777-4777-8777-777777777777',titre:'Cap réseau',type_cible:'reseau',agence_id:null,date_debut:'2026-09-01',date_fin:'2026-09-30',statut_objectif:'actif',type_periodicite:'mensuel',cible_montant_smart:1000}
    await context.route('**/api/agent/exports',async route=>{exports.push(route.request().postDataJSON());await route.fulfill({status:200,headers:{'Content-Type':'application/octet-stream','Content-Disposition':'attachment; filename="rapport.xlsx"'},body:'synthetic-download'})})
    await context.route(`${url}/**`,async route=>{
      const req=route.request(),u=new URL(req.url());let body=[],status=200
      if(u.pathname.includes('/auth/v1/'))body=user
      else if(u.pathname.includes('/rpc/')){
        const name=u.pathname.split('/').pop(),args=req.postDataJSON();calls.push({name,args})
        if(name==='rapport_reseau')body={...network,periode:{debut:args.p_date_debut,fin:args.p_date_fin},statuts:args.p_statuts,filtres:{agence_id:args.p_agence_id,equipe_id:args.p_equipe_id,membre_id:args.p_membre_id,agence_active:args.p_agence_active}}
        else if(name==='classement_reseau')body={ok:true,classement:[{rang:1,agence_nom:'Agence test',total_smart:1000}]}
        else if(name==='reseau_file_traitement')body={ok:true,total_filtre:21,compteurs:{en_attente:21,a_corriger:0,validees:0},fiches:[{fiche_id:id,agent_id:member,prenom:'Collecteur',nom:'Test',date:'2026-09-20',agence_nom:'Agence test',statut:'en_attente',smart:100,caisse:90},{fiche_id:member,agent_id:member,prenom:'Autre',nom:'Collecteur',date:'2026-09-19',agence_nom:'Agence test',statut:'en_attente',smart:100,caisse:90}]}
        else if(name==='ecarts_ouverts')body={ok:true,total_filtre:1,compteurs:{nb_manquants_ouverts:1,nb_surplus_ouverts:0,total_manquant_restant:10,total_surplus_restant:0},ecarts:[{fiche_id:id,agent_id:member,prenom:'Collecteur',nom:'Test',date:'2026-09-20',smart:100,caisse:90,manquant_restant:10,surplus_restant:0}]}
        else if(name==='rapport_fiche_journaliere')body={ok:true,entete:{agent:'Collecteur Test',agence:'Agence test',equipe:'Équipe test',date:'2026-09-20',statut:'en_attente'},montants:{smart:100,caisse:90,regularise:0,restant:10,surplus_restant:0},activite:{},reactivations:[],augmentations:[],assurances:[]}
        else if(name==='objectifs_collectifs' || name==='agent_objectifs_avec_progression')body={ok:true,objectifs:[{id:'progress',titre:'Objectif progression',date_debut:'2026-09-01',date_fin:'2026-09-30',progressions:[{champ:'smart',libelle:'SMART',cible:1000,realise:1500,pct:150,mesurable:true},{champ:'future',libelle:'Indicateur futur',cible:10,realise:null,pct:null,mesurable:false}]}]}
        else throw Error('Unexpected RPC '+name)
      }else if(u.pathname.endsWith('/agents'))body=req.headers().accept?.includes('object')?{id,prenom:'Direction',nom:'Test',telephone:'',role:'dg',actif:true,statut:'actif'}:[{id:member,prenom:'Collecteur',nom:'Test',agence_id:id,equipe_id:id,role:'chef',actif:true,statut:'actif'}]
      else if(u.pathname.endsWith('/agences'))body=[{id,nom:'Agence test',actif:true}]
      else if(u.pathname.endsWith('/equipes'))body=[{id,nom:'Équipe test',agence_id:id}]
      else if(u.pathname.endsWith('/objectifs')){if(req.method()==='GET')body=[goal];else {writes.push(req.postDataJSON());status=writeFail?403:200;body=writeFail?{message:'Refus simulé'}:{id:goal.id}}}
      await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)})
    })
    const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(/containing a .key.|React keys|Hydration failed|hydration mismatch/i.test(msg.text()))consoleErrors.push(msg.text())})
    await page.goto((process.env.TEST_BASE_URL||'http://localhost:3000')+'/dashboard/dg')
    await page.getByRole('heading',{name:'Vue d’ensemble',exact:true}).waitFor()
    await page.getByRole('heading',{name:'Par agence',exact:true}).waitFor()
    const graph=page.getByRole('region',{name:'Repère visuel du périmètre sélectionné'})
    await graph.getByRole('button',{name:'Masquer le graphique'}).waitFor()
    await graph.getByRole('button',{name:'Masquer le graphique'}).click()
    await page.reload();await page.getByRole('heading',{name:'Par agence',exact:true}).waitFor()
    await graph.getByRole('button',{name:'Afficher le graphique'}).waitFor()
    await graph.getByRole('button',{name:'Afficher le graphique'}).click()
    await graph.getByLabel('Indicateur du graphique').selectOption('total_caisse')
    await page.screenshot({path:'.next/lot9-validation/dg-charts-desktop.png',fullPage:true})
    await page.getByRole('button',{name:'Exporter un rapport',exact:true}).click()
    const exportDialog=page.getByRole('dialog',{name:'Préparer le rapport'})
    await exportDialog.getByLabel('Rapport personnalisé',{exact:true}).check()
    for(const box of await exportDialog.getByRole('checkbox').all()) await box.uncheck()
    assert.ok(await exportDialog.getByRole('button',{name:'Télécharger le rapport'}).isDisabled())
    await exportDialog.getByLabel('Par agence',{exact:true}).check()
    await exportDialog.getByLabel('Assurances',{exact:true}).check()
    await exportDialog.getByLabel('Format',{exact:true}).selectOption('xlsx')
    const download=page.waitForEvent('download');await exportDialog.getByRole('button',{name:'Télécharger le rapport'}).click();await download
    assert.deepEqual(exports.at(-1).sections,['agences','assurances']);assert.equal(exports.at(-1).format,'xlsx')
    await exportDialog.getByLabel('Rapport complet',{exact:true}).check()
    const full=page.waitForEvent('download');await exportDialog.getByRole('button',{name:'Télécharger le rapport'}).click();await full
    assert.equal(exports.at(-1).sections,undefined)
    await exportDialog.getByRole('button',{name:'Fermer',exact:true}).click()
    await page.getByRole('button',{name:'Suivant',exact:true}).click()
    await page.getByText('26 lignes · Page 2/2').waitFor()
    const analysis=page.getByRole('navigation',{name:'Analyses de la vue d’ensemble'})
    await analysis.getByRole('button',{name:'Équipes',exact:true}).click()
    await analysis.getByRole('button',{name:'Agences',exact:true}).click()
    await page.getByText('26 lignes · Page 2/2').waitFor()
    await page.getByLabel('Rechercher dans Par agence').fill('supplémentaire 24')
    await page.getByText('1 résultat(s) sur 26 · recherche dans ce tableau').waitFor()
    await page.getByLabel('Rechercher dans Par agence').fill('')
    await page.getByLabel('Agence',{exact:true}).selectOption(id)
    await page.getByLabel('Équipe',{exact:true}).selectOption(id)
    await page.getByRole('heading',{name:'Par agence',exact:true}).waitFor()
    assert.equal(calls.filter(c=>c.name==='rapport_reseau').at(-1).args.p_equipe_id,id)
    await page.getByRole('navigation',{name:'Analyses de la vue d’ensemble'}).getByRole('button',{name:'Classements',exact:true}).click()
    await page.getByRole('heading',{name:'Résultats',exact:true}).waitFor()
    assert.equal(calls.filter(c=>c.name==='classement_reseau').at(-1).args.p_equipe_id,null)
    await page.getByRole('navigation',{name:'Analyses de la vue d’ensemble'}).getByRole('button',{name:'Agences',exact:true}).click()
    assert.equal(await page.getByRole('heading',{name:'Par équipe',exact:true}).count(),0)
    await page.getByRole('navigation',{name:'Analyses de la vue d’ensemble'}).getByRole('button',{name:'Équipes',exact:true}).click()
    await page.getByRole('heading',{name:'Par équipe',exact:true}).waitFor()
    await page.getByRole('navigation',{name:'Analyses de la vue d’ensemble'}).getByRole('button',{name:'Agences',exact:true}).click()

    await page.getByLabel('Inclure les fiches non validées').check()
    await page.getByRole('heading',{name:'Par agence',exact:true}).waitFor()
    assert.equal(calls.filter(c=>c.name==='rapport_reseau').at(-1).args.p_statuts.length,3)
    await page.getByRole('button',{name:'Fiches',exact:true}).click()
    await page.getByRole('button',{name:'Suivant',exact:true}).click()
    await page.getByText('Page 2 sur 2').waitFor()
    assert.equal(calls.filter(c=>c.name==='reseau_file_traitement').at(-1).args.p_page,2)
    assert.equal(await page.getByRole('button',{name:/Valider|Régulariser/}).count(),0)
    const opener=page.getByRole('button',{name:'Consulter →',exact:true}).first()
    await opener.click()
    const drawer=page.getByRole('dialog');await drawer.waitFor()
    assert.ok(await drawer.evaluate(e=>e.getBoundingClientRect().top===0))
    await drawer.getByRole('heading',{name:'Synthèse',exact:true}).waitFor()
    await page.screenshot({path:'.next/lot9-validation/dg-drawer-desktop.png'})
    await drawer.getByRole('button',{name:'Fiche suivante',exact:true}).click()
    await drawer.getByRole('heading',{name:'Autre Collecteur',exact:true}).waitFor()
    await drawer.getByRole('button',{name:'Régularisations',exact:true}).click()
    await drawer.getByRole('heading',{name:'Historique des régularisations'}).waitFor()
    await page.keyboard.press('Escape');await drawer.waitFor({state:'detached'})
    assert.ok(await opener.evaluate(e=>e===document.activeElement))
    await page.getByText('Page 2 sur 2').waitFor()

    await page.getByRole('button',{name:'Écarts ouverts',exact:true}).click()
    await page.getByText('Stock des écarts non soldés').waitFor()
    await page.getByRole('heading',{name:'1 fiche(s)',exact:true}).waitFor()
    assert.equal(calls.filter(c=>c.name==='ecarts_ouverts').at(-1).args.p_date_debut,null)
    await page.getByRole('button',{name:'Objectifs',exact:true}).click()
    await page.getByText('Objectif progression',{exact:true}).click()
    await page.getByRole('img',{name:'SMART : 150 %, cible 100 %'}).waitFor()
    await page.getByText('Indicateur futur : non mesurable',{exact:true}).waitFor()
    await page.getByRole('button',{name:'Modifier',exact:true}).click()
    assert.ok(await page.getByRole('dialog').getByLabel('Périmètre',{exact:true}).isDisabled())
    await page.getByRole('dialog').getByLabel('Titre',{exact:true}).fill('Titre modifié')
    await page.getByRole('button',{name:'Enregistrer',exact:true}).click()
    await page.getByText('Objectif non enregistré. Vérifiez les droits et la cible.',{exact:true}).waitFor()
    assert.ok(!Object.hasOwn(writes.at(-1),'type_cible'));assert.ok(!Object.hasOwn(writes.at(-1),'agence_id'))
    writeFail=false;await page.getByRole('button',{name:'Enregistrer',exact:true}).click()
    await page.getByRole('dialog').waitFor({state:'detached'})
    await page.getByRole('button',{name:'Statistiques',exact:true}).click()
    await page.getByRole('img',{name:'Évolution de la collecte, SMART et caisse en FCFA'}).waitFor()
    await page.getByRole('navigation',{name:'Rubriques statistiques'}).getByRole('button',{name:'Activité commerciale',exact:true}).click()
    await page.getByLabel('Niveau commercial').selectOption('equipe')
    await page.getByLabel('Indicateur commercial').selectOption('assurances_montant')
    await page.getByText('Aucune donnée pour cette sélection.',{exact:true}).waitFor()
    await page.getByRole('navigation',{name:'Rubriques statistiques'}).getByRole('button',{name:'Évolution',exact:true}).click()
    await page.getByRole('heading',{name:'SMART · Six mois jusqu’à la date de fin'}).waitFor()
    await page.screenshot({path:'.next/lot9-validation/dg-desktop.png',fullPage:false})
    await page.setViewportSize({width:390,height:844})
    await page.getByRole('button',{name:'Ouvrir le menu'}).click()
    await page.getByRole('button',{name:'Vue d’ensemble',exact:true}).click()
    await page.getByRole('heading',{name:'Par agence',exact:true}).waitFor()
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1))
    await page.screenshot({path:'.next/lot9-validation/dg-mobile.png',fullPage:false})
    await page.getByRole('button',{name:'Ouvrir le menu'}).click()
    await page.getByRole('navigation',{name:'Navigation principale'}).getByRole('button',{name:'Fiches',exact:true}).click()
    await page.getByRole('button',{name:'Consulter →',exact:true}).first().click()
    const mobileDrawer=page.getByRole('dialog');await mobileDrawer.waitFor()
    assert.equal(Math.round(await mobileDrawer.evaluate(e=>e.getBoundingClientRect().width)),390)
    await mobileDrawer.getByRole('heading',{name:'Synthèse',exact:true}).waitFor()
    await page.screenshot({path:'.next/lot9-validation/dg-drawer-mobile.png'})
    await mobileDrawer.getByRole('button',{name:'Fermer le détail'}).click()
    await page.reload();await page.getByRole('heading',{name:'Vue d’ensemble',exact:true}).waitFor()
    await page.getByRole('heading',{name:'Par agence',exact:true}).waitFor()
    assert.deepEqual(consoleErrors,[])
    assert.deepEqual(errors,[])
    console.log('PASS DG UX (tabs, drawer, Escape/focus, mobile, console key/hydration): filtres, classement agence indépendant, prévisualisation, pagination serveur, stock historique, consultation seule, objectif échec/succès sans scope, PC/mobile sans débordement ni erreur React.')
  }finally{await browser.close()}
}
main().catch(e=>{console.error(e);process.exitCode=1})
